Microphones via AOP.
AsahiLinux/linux pull request #342
Opened 2024-11-09 18:03 UTC by WhatAmISupposedToPutHere

This adds the AOP driver, microphone support, lid angle sensor driver, and ambient light sensor driver (disabled pending some m1n1 work).

Obsoletes #151

Draft for the following reasons:
1. Does not work on base m1 yet, those need a sep driver (coming soontm).
2. The mic output is basically useless without correct userspace configs (also soontm).

2024-11-12 04:10 UTC, jacksongoode commented on arch/arm64/boot/dts/apple/t602x-die0.dtsi
> +		compatible = "apple,t6020-admac2", "apple,t6020-admac", "apple,admac", "apple,admac";
One of these should be `apple,admac2`, right?

2024-11-24 02:29 UTC, chadmed requested changes
Just a couple of nits in the driver itself, but apart from those we need to make sure we're setting:
- `snd_card.shortname` (e.g. `MacBook Pro J314 HPAI`)
- `snd_card.longname` (e.g. `MacBook Pro J314 High-Power Audio Interface`)
- `snd_card.id` (e.g. `AppleJ314HPAI`)

This will align with what we do for macaudio and DCP, and makes doing UCM and DSP rules easier.

2024-11-24 02:29 UTC, chadmed commented on sound/soc/apple/aop_audio.rs
> +            chassis[0].make_ascii_uppercase();
Is this really necessary if the device tree is correct? We control the DTs, we should just make sure the value in the DT is correct.

2024-11-24 02:29 UTC, chadmed commented on sound/soc/apple/aop_audio.rs
> +        }
Is doing this twice intentional? Also, given that we set `snd_card.driver` to something entirely different below, do either of these blocks actually do anything?

2024-11-24 02:29 UTC, chadmed commented on sound/soc/apple/aop_audio.rs
> +        }
This should just be `aop` anyway.

2024-11-24 14:39 UTC, jannau commented
I've merged everything except the device tree changes into bits/ branches. Most of it into `bits/190-rust` and `bits/250-aop` but fixups in there respective bits/* branches. I'm not happy with the split-up as merging `bits/250-aop` needs manual conflict resolution. I can't think of anything better though. Will get easier when we upstream more changes.

I did some minimal fixups. Can you please send 85e9396f80328f839c8864308af9ba91d128d970 ("dmaengine: apple-admac: Avoid accessing registers in probe") (without the compatible addition) as soon as possible. If I remember correctly special power sequencing requirements do not warrant a different  compatible. If we fix upstream now we can upstream aop-admac with the same compatible string later. Downstream we will keep "apple,admac2" for now.

For commit b63a09090638 ("rust: Only export module id tables if building as module") please reply to https://lore.kernel.org/rust-for-linux/20241022213221.2383-5-dakr@kernel.org/

2024-12-11 23:30 UTC, clintaire commented
Can the necessary configurations for `snd_card` fields be abstracted into a reusable module or script to avoid repetitive work and standardize the approach across different hardware?

2024-12-12 12:11 UTC, WhatAmISupposedToPutHere commented
> Can the necessary configurations for `snd_card` fields be abstracted into a reusable module or script to avoid repetitive work and standardize the approach across different hardware?

Sorry i am not quite sure i understand. Are you asking as to whether there will be rust bindings for alsa? If so - yes, eventually, and those may or may not come from me.

2024-12-26 13:24 UTC, rosvall commented
> Draft, since the mic output is basically useless without correct userspace configs (coming soontm).

I've played a with this for a bit, and at least on my m1 macbook air, the sound is absolutely usable!

Here's a short 3 channel recording: [mic_test_j313.wav.zip](https://github.com/user-attachments/files/18252942/mic_test_j313.wav.zip)

Please merge the devicetree bindings and let people have some fun with it.

2024-12-26 13:44 UTC, WhatAmISupposedToPutHere commented
> > Draft, since the mic output is basically useless without correct userspace configs (coming soontm).
> 
> I've played a with this for a bit, and at least on my m1 macbook air, the sound is absolutely usable!
> 
> Here's a short 3 channel recording: [mic_test_j313.wav.zip](https://github.com/user-attachments/files/18252942/mic_test_j313.wav.zip)
> 
> Please merge the devicetree bindings and let people have some fun with it.

How much did you boost the signal?

2024-12-26 13:50 UTC, rosvall commented
> > > Draft, since the mic output is basically useless without correct userspace configs (coming soontm).
> > 
> > 
> > I've played a with this for a bit, and at least on my m1 macbook air, the sound is absolutely usable!
> > Here's a short 3 channel recording: [mic_test_j313.wav.zip](https://github.com/user-attachments/files/18252942/mic_test_j313.wav.zip)
> > Please merge the devicetree bindings and let people have some fun with it.
> 
> How much did you boost the signal?

It's not boosted. I've just set configuration profile to "Pro Audio" and gain to 0dB in pavucontrol, and recorded with `arecord -D pipewire -d 10 -r 48000 -v -f FLOAT_LE -c 3 mic_test_j313.wav`

2024-12-26 13:51 UTC, WhatAmISupposedToPutHere commented
> > > > Draft, since the mic output is basically useless without correct userspace configs (coming soontm).
> > > 
> > > 
> > > I've played a with this for a bit, and at least on my m1 macbook air, the sound is absolutely usable!
> > > Here's a short 3 channel recording: [mic_test_j313.wav.zip](https://github.com/user-attachments/files/18252942/mic_test_j313.wav.zip)
> > > Please merge the devicetree bindings and let people have some fun with it.
> > 
> > 
> > How much did you boost the signal?
> 
> It's not boosted. I've just set configuration profile to "Pro Audio" and gain to 0dB in pavucontrol, and recorded with `arecord -D pipewire -d 10 -r 48000 -v -f FLOAT_LE -c 3 mic_test_j313.wav`

Well, this is not how it works on, say j314, where a boost of 50-ish dba is required for the signal to be audible.

2024-12-26 20:52 UTC, rosvall commented
> Well, this is not how it works on, say j314, where a boost of 50-ish dba is required for the signal to be audible.

Is it broken on every j314?

2024-12-26 21:38 UTC, WhatAmISupposedToPutHere commented
> > Well, this is not how it works on, say j314, where a boost of 50-ish dba is required for the signal to be audible.
> 
> Is it broken on every j314?

At least two of them. j415 also needs 20-30 dba of boost.

2024-12-26 23:26 UTC, chadmed commented
That mic signal is useless and almost silent. J313 will need boosting too.

2025-01-03 19:00 UTC, jannau commented
device nodes (disabled) included in asahi-6.12.8-1, going to close this PR
trivial patches to enable the mics are in https://github.com/jannau/linux/commits/mics-asahi-6.12.8-1/

changes compared to this PR:
- enable mics on M1 imacs
- enable sep only on t8103-j*

2025-01-03 19:00 UTC, closed without merging