Apple M1 WDT support
AsahiLinux/linux pull request #4
Opened 2021-08-08 16:26 UTC by pipcet

(Currently untested; will comment once I can test it).

This should be useful as it allows rebooting both automatically and per SysRq.

2021-08-08 16:46 UTC, svenpeter42 requested changes
Alright, let's see how this workflow works for us. Thanks for the first PR :-)

I don't know much about the watchdog subsystem. I've essentially just commented on general things based on the reviews I got on my upstreaming attempts so far.

2021-08-08 16:46 UTC, svenpeter42 commented on drivers/watchdog/apple_wdt.c
> +#define WDT_RATE		(24 * 1000 * 1000)
i wouldn't hardcode any default and just require a clock to be present

2021-08-08 16:46 UTC, svenpeter42 commented on drivers/watchdog/apple_wdt.c
> +	wdt->clk = devm_clk_get_optional(dev, NULL);
as mentioned above, I'd just require a clock to be present and take its frequency

2021-08-08 16:46 UTC, svenpeter42 commented on drivers/watchdog/apple_wdt.c
> +	{ .compatible = "apple,wdt" },
this should allow "apple,t8103-wdt" (and possibly "apple,wdt" if we know that this has been around for a while). the idea is to always have a specific compatible for the SoC we're working on just in case we need to add quirks, etc. later that were only introduced in this specific version.
if some older SoC uses "apple,wdt" then that new quirk wouldn't be applied there.

probably not relevant for the wdt, but i think it should be done to remain consistent anyway.

2021-08-08 16:46 UTC, svenpeter42 commented on drivers/watchdog/apple_wdt.c
> +#define   WDT_CONTROL_TRIGGER	0x04
(nit) if this is a bit inside a register usually BIT(2) is used

2021-08-08 16:46 UTC, svenpeter42 commented on drivers/watchdog/apple_wdt.c
> +	if (s > U32_MAX / wdt->rate)
not sure how watchdogs usually work, but my first instinct would be to just return -EINVAL in this case

2021-08-08 16:46 UTC, svenpeter42 commented on arch/arm64/boot/dts/apple/t8103.dtsi
> +		        compatible = "apple,wdt";
this needs to be documented in documentation/devicetree/bindings/watchdog. you can probably just copy one of the .yml files with some very minor changes

2021-08-08 16:58 UTC, alyssarosenzweig commented on drivers/watchdog/apple_wdt.c
> +	{ .compatible = "apple,wdt" },
I'm... not sure I agree? If new SoCs need new quirks, they can get more specific compatibles, I don't see that as a reason to complicate the compatibles now?

2021-08-08 17:08 UTC, alyssarosenzweig commented on drivers/watchdog/apple_wdt.c
> +		comparator = s * wdt->rate;
It might be clearer and faster to avoid the integer division and just directly compute the product (since we have fast 32x32 = 64 multiplies on arm64):

```
u64 comparator = (u64) s * (u64) wdt->rate;

if (comparator > U32_MAX) {
     clamp or einval
}
```

2021-08-08 17:11 UTC, alyssarosenzweig commented on drivers/watchdog/apple_wdt.c
> +MODULE_AUTHOR("Pip Cet <pipcet@gmail.com>");
Just to confirm -- Pip Cet is your real (meatspace) name, yeah?

2021-08-08 17:20 UTC, alyssarosenzweig commented on drivers/watchdog/apple_wdt.c
> +		comparator = s * wdt->rate;
(Edited to use mul_u32_u32)

2021-08-08 18:35 UTC, svenpeter42 commented on drivers/watchdog/apple_wdt.c
> +	{ .compatible = "apple,wdt" },
https://lore.kernel.org/lkml/CAL_Jsq+V74tMGJ==OVdsssfqTTa3TrFujfRjj0174uZNonpQSA@mail.gmail.com/ that's probably a better explanation than mine. 

> The important part is *always* having an SoC specific compatible so
you can deal with any quirk or feature without having to change the
DTB. Everyone says blocks are 'the same' until they aren't.

2021-08-08 18:46 UTC, alyssarosenzweig commented on drivers/watchdog/apple_wdt.c
> +	{ .compatible = "apple,wdt" },
Fair enough, retracted.

2021-08-08 22:34 UTC, pipcet commented
Tested, and it appears to work with the current version.
* Reboots if I create a watchdog device and write to it, then stop for three minutes
* SysRq reboots
* doesn't reboot if I start watchdog(8) and keep it running
* does reboot if I kill -STOP the watchdog process
* appears to set timeout correctly (as verified by memtool)
* reboots after the right timeout (as verified by modifying it in watchdog.conf)

2021-08-08 22:34 UTC, pipcet commented
Should I squash commits, or would we do that when merging?

2021-08-08 22:48 UTC, alyssarosenzweig commented
> Should I squash commits, or would we do that when merging?

Please squash into the logical series. (We can't do that automatically when merging). For this PR, that means three commits:

Subject: [PATCH 1/7] watchdog: apple_wdt: Add support for Apple M1 WDT
Subject: [PATCH 2/7] arm64: apple: Add WDT to devicetree
Subject: [PATCH 4/7] bindings/watchdog: apple,t8103-wdt.txt: bindings for
 Apple M1 WDT

with the other 4 commits squashed into those 3 as appropriate.

2021-08-08 22:52 UTC, pipcet commented on drivers/watchdog/apple_wdt.c
> +	if (s > U32_MAX / wdt->rate)
I'm inclined to agree; I did it that way because other drivers also clamp the value.

2021-08-08 22:57 UTC, pipcet commented on arch/arm64/boot/dts/apple/t8103.dtsi
> +		wdt: wdt@23d2b0000 {
This should probably be "watchdog@23d2b0000"? I've yet to figure out this yaml schema stuff, but that's what watchdog.yaml appears to imply to me...

2021-08-08 23:13 UTC, pipcet commented on Documentation/devicetree/bindings/watchdog/apple,t8103-wdt.yaml
> +$schema: http://devicetree.org/meta-schemas/core.yaml#
The file I stole this from had a
```
$id: ...#
```
line here. Is that required? It looks like something you have to register somehow, so I'm reading up on that...

2021-08-09 06:16 UTC, svenpeter42 commented on drivers/watchdog/apple_wdt.c
> +	if (s > U32_MAX / wdt->rate)
then clamping is probably better!

2021-08-09 06:18 UTC, svenpeter42 commented on arch/arm64/boot/dts/apple/t8103.dtsi
> +		wdt: wdt@23d2b0000 {
Yes. What I understand is that the format is usually "whatever_is_convenient_for_xrefs_in_the_dt: generic_name@address". I think the idea is that generic_name is available inside kernel code and older drivers sometimes relied on that to identify nodes which is not supposed to happen

2021-08-09 06:23 UTC, svenpeter42 commented on Documentation/devicetree/bindings/watchdog/apple,t8103-wdt.yaml
> +$schema: http://devicetree.org/meta-schemas/core.yaml#
Yes, no need to register it anywhere though. It gets "registered" when the commit is merged upstream. 
I'd call this file "apple,wdt.yml" btw. and then use "$id: http://devicetree.org/schemas/watchdog/apple,wdt.yaml#". That format was accepted for my DART patchset.

You can also run `make dt_binding_check` and `make dtbs_check` to verify your changes.

And one final minor nit: The commit should have the prefix "dt-bindings: watchdog:" and needs to come before the other commits.

2021-08-09 06:27 UTC, svenpeter42 commented on Documentation/devicetree/bindings/watchdog/apple,t8103-wdt.yaml
> +unevaluatedProperties: false
I think you can even use "additionalProperties: false" here which I believe is a bit stronger

2021-08-09 06:34 UTC, svenpeter42 commented on Documentation/devicetree/bindings/watchdog/apple,t8103-wdt.yaml
> +# SPDX-License-Identifier: GPL-2.0-only
and yet another nit, this time actually the last one i promise :-)

dt bindings should always be dual-licensed (`(GPL-2.0-only OR BSD-2-Clause)`) since they are also consumed by other software like *BSD or u-boot.

2021-08-09 07:29 UTC, pipcet commented on Documentation/devicetree/bindings/watchdog/apple,t8103-wdt.yaml
> +$schema: http://devicetree.org/meta-schemas/core.yaml#
Thanks for all the nits! They're great and help a lot, and hopefully there will be slightly fewer of them in the next PR :-)

2021-08-09 07:53 UTC, pipcet commented on Documentation/devicetree/bindings/watchdog/apple,wdt.yaml
> +        reg = <0x3bd20000 0x4000>;
Is it okay to use a 1+1-celled reg property in the example, even though the actual DT entry has 2+2 cells?

2021-08-09 12:56 UTC, alyssarosenzweig commented
To this best of my abilities `Reviewed-by: Alyssa Rosenzweig <alyssa@rosenzweig.io>`

2021-08-09 18:30 UTC, svenpeter42 commented on Documentation/devicetree/bindings/watchdog/apple,wdt.yaml
> +        reg = <0x3bd20000 0x4000>;
that's what I did for the DART driver as well an no one complained there :)

2021-08-09 18:32 UTC, svenpeter42 commented
there's typo in the dt-binding commit message where you have .txt instead of .yml (and I think you can drop the whole "apple,wdt.txt" part anyway). LGTM otherwise!

2021-08-09 19:28 UTC, pipcet commented
Thank you very much! `checkpatch` did find stuff, too, but it runs cleanly now.

2021-08-09 19:30 UTC, svenpeter42 commented
Nice! Looks good now i think. I’d merge it but given that Marcan wants to built some automatic rebasing hooks and create some feature branches I think it makes sense to wait for that.

I think this could be submitted to upstream as well now :-)

2021-08-11 17:05 UTC, jgouly commented on drivers/watchdog/apple_wdt.c
> +	wdt->reg = devm_ioremap_resource(dev, res);
You could use the helper `devm_platform_ioremap_resource(pdev, 0)` to replace `platform_get_resource` followed by `devm_ioremap_resource`.

2021-08-11 20:47 UTC, pipcet commented on drivers/watchdog/apple_wdt.c
> +	wdt->reg = devm_ioremap_resource(dev, res);
Thank you very much! Done, please let me know if you notice anything else that's odd.

2021-10-17 17:12 UTC, closed without merging