pwm: Add new pwm driver for ARM Macs
AsahiLinux/linux pull request #57
Opened 2022-10-06 22:48 UTC by WhatAmISupposedToPutHere

Arm macs have a PWM controller that is hooked up to the keyboard backlight. This patch adds the controller driver and device tree bindings using pwm-leds.

2022-10-11 23:36 UTC, nsapa commented on drivers/pwm/pwm-apple.c
> +#define PWM_APPLY_MAGIC 0x4239
Unused define?

2022-10-16 12:59 UTC, svenpeter42 commented on Documentation/devicetree/bindings/pwm/pwm-apple.yaml
> +    const: apple,s5l-fpwm
This should have the usual “tXXXX-fpwm” SoC specific compatibles as well for the unlikely case that we need to quirk the driver in the future

2022-10-16 13:01 UTC, svenpeter42 commented on drivers/pwm/pwm-apple.c
> +	struct clk *clk;
minor nit: I think you can even drop the struct clk from here since you only need it in probe

2022-10-16 13:02 UTC, svenpeter42 commented on drivers/pwm/pwm-apple.c
> +	on_cycles = fpwm->clkrate * state->duty_cycle / NSEC_PER_SEC;
another minor nit: these should probably also be inside the if block below to make it clear to the reader that they are only used when enabling

2022-10-16 13:43 UTC, jannau reviewed
looks overall good, left some small remarks as commits. Tested on j493 (M2 Macbook pro 13") against asahi-wip

Please split the commit into multiple commits. A good split would be
1. dt-bindings
2. PWM driver
3. dts changes (probably best splitted into 3 commits for t8103, t600x and t8110)

It misses a MAINTAINER update. Upstream wants that in the commit with the driver but @marcan prefers it as separate commit to make rebasing simpler

2022-10-16 13:43 UTC, jannau commented on Documentation/devicetree/bindings/pwm/pwm-apple.yaml
> +
The properties list misses `power-domains`. `make dtbs_check` will verify the dts against the schema

2022-10-16 13:43 UTC, jannau commented on Documentation/devicetree/bindings/pwm/pwm-apple.yaml
> +      status = "disabled";
the `status` property doesn't add any information to the example and should probably removed

2022-10-16 13:43 UTC, jannau commented on Documentation/devicetree/bindings/pwm/pwm-apple.yaml
> +    fpwm1: fpwm@235044000 {
the node name (the part before the `@$address`) should be the generic `pwm`. The other schema files import this restriction trough
```
allOf:
  - $ref: pwm.yaml#
```

2022-10-16 13:43 UTC, jannau commented on arch/arm64/boot/dts/apple/t8103.dtsi
> +#include <dt-bindings/leds/common.h>
nit: this include could be moved to the device dts files defining keyboard led

2022-10-16 13:43 UTC, jannau commented on drivers/pwm/pwm-apple.c
> +	if (state->enabled) {
`on/off_cycles` calculation can be moved into `if (state->enabled)`

2022-10-16 13:43 UTC, jannau commented on drivers/pwm/pwm-apple.c
> +	    + state->duty_cycle;
wouldn't it make more sense to calculate this as `(on_cycles + off_cycles) / fpwm->clkrate * NSEC_PER_SEC`?

2022-10-16 13:43 UTC, jannau commented on drivers/pwm/pwm-apple.c
> +	ret = clk_prepare_enable(pwm->clk);
there is `devm_clk_get_enabled()` combining this two steps.

2022-10-16 13:43 UTC, jannau commented on Documentation/devicetree/bindings/pwm/pwm-apple.yaml
> +maintainers: []
As far as I can see it's accepted to put mailing lists as dt-bindings maintainer. Please add `asahi@lists.linux.dev`

2022-10-16 19:49 UTC, WhatAmISupposedToPutHere commented on drivers/pwm/pwm-apple.c
> +	ret = clk_prepare_enable(pwm->clk);
devm_clk_get_enabled only exists in asahi-wip, and not asahi, retargeting the pull request to that branch

2022-10-17 10:14 UTC, marcan requested changes
This looks generally good, just a few comments. You also need to sign off your commits for upstreaming (the DCO bot tells you how).

2022-10-17 10:14 UTC, marcan commented on drivers/pwm/pwm-apple.c
> +// SPDX-License-Identifier: GPL-2.0
Any chance we could license this as `GPL-2.0 OR MIT` (or `GPL-2.0-only OR MIT`)? This is a pretty trivial driver, but it's nice leaving the door open for BSD & co to pull code directly from our drivers.

(FYI, if you do this, the correct MODULE_LICENSE is `MODULE_LICENSE("Dual MIT/GPL");`)

2022-10-17 10:14 UTC, marcan commented on drivers/pwm/pwm-apple.c
> +static void apple_pwm_clk_disable_unprepare(void *data)
This looks like dead code.

2022-10-17 10:14 UTC, marcan commented on Documentation/devicetree/bindings/pwm/pwm-apple.yaml
> +  - asahi@lists.linux.dev
This should probably list an actual person and not just the list (you can throw it at me if you don't want to sign up :))

2022-11-22 22:32 UTC, WhatAmISupposedToPutHere commented
this was merged

2022-11-22 22:32 UTC, closed without merging